@AKS_IP = 20.54.124.190

###

GET http://{{AKS_IP}}/api/user/

###

POST http://{{AKS_IP}}/api/user/login
content-type: application/json

{ "userName": "sample", "password": "user" }

###

POST http://{{AKS_IP}}/api/user/get-user-list

###

GET http://{{AKS_IP}}/api/campaign/

###

GET http://{{AKS_IP}}/api/campaign/get-current

###

###
